# Generated by Django 4.1.2 on 2022-10-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knn_data',
            fields=[
                ('Rain_Over', models.IntegerField(db_column='Rain_over', max_length=10, primary_key=True, serialize=False)),
                ('New_city_id', models.CharField(db_column='New_city_id', max_length=100)),
            ],
            options={
                'db_table': 'Knn_data',
            },
        ),
        migrations.CreateModel(
            name='noral_Data',
            fields=[
                ('Old_city_id', models.CharField(db_column='Old_city_id', max_length=100, primary_key=True, serialize=False)),
                ('New_city_id', models.CharField(db_column='New_city_id', max_length=100)),
                ('city_name', models.CharField(db_column='city_name', max_length=100)),
                ('data_date', models.CharField(db_column='data_date', max_length=100)),
                ('data', models.CharField(db_column='data', max_length=100)),
            ],
            options={
                'db_table': 'dataChange',
            },
        ),
        migrations.CreateModel(
            name='today_Data',
            fields=[
                ('city_id', models.CharField(db_column='city_id', max_length=100, primary_key=True, serialize=False)),
                ('city_name', models.CharField(db_column='city_name', max_length=100)),
                ('text_day', models.CharField(db_column='text_day', max_length=100)),
                ('high', models.IntegerField(db_column='high', max_length=11)),
                ('low', models.IntegerField(db_column='low', max_length=11)),
                ('humidity', models.IntegerField(db_column='humidity', max_length=11)),
                ('rainfall', models.CharField(db_column='rainfall', max_length=100)),
                ('wind_speed', models.CharField(db_column='wind_speed', max_length=100)),
                ('date', models.CharField(db_column='date', max_length=100)),
            ],
            options={
                'db_table': 'today_data',
            },
        ),
        migrations.CreateModel(
            name='User_manager',
            fields=[
                ('User_id', models.IntegerField(auto_created=True, db_column='User_id', max_length=255, primary_key=True, serialize=False)),
                ('User_name', models.CharField(db_column='User_name', max_length=255)),
                ('User_Permission', models.IntegerField(db_column='User_Permission')),
                ('User_account', models.CharField(db_column='User_Account', max_length=255)),
                ('User_Password', models.CharField(db_column='User_Password', max_length=255)),
                ('User_mail', models.CharField(db_column='User_mail', max_length=255)),
                ('User_Zone', models.CharField(db_column='User_zone', max_length=255)),
            ],
            options={
                'db_table': 'User_manager',
            },
        ),
        migrations.CreateModel(
            name='Zone_Data',
            fields=[
                ('Old_city_id', models.IntegerField(db_column='Old_city_id', max_length=11, primary_key=True, serialize=False)),
                ('New_city_id', models.CharField(db_column='New_city_id', max_length=100)),
                ('city_name', models.CharField(db_column='city_name', max_length=100)),
            ],
            options={
                'db_table': 'newlinkold',
            },
        ),
    ]
